-- MySQL Script generated by MySQL Workbench
-- ср, 20-сер-2014 23:30:45 +0300
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PhotoLibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhotoLibrary` DEFAULT CHARACTER SET utf8 ;
USE `PhotoLibrary` ;

-- -----------------------------------------------------
-- Table `PhotoLibrary`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoLibrary`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `last_seen` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhotoLibrary`.`Passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoLibrary`.`Passwords` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Passwords_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `PhotoLibrary`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhotoLibrary`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PhotoLibrary`.`Photos` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `source` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`photo_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
